import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { unzipSync } from "fflate";

const SOURCE_URL = "https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip";
const REGION_BITS = new Map([
  ["G", 1 << 0],
  ["H", 1 << 1],
  ["M", 1 << 2],
  ["T", 1 << 3],
  ["J", 1 << 4],
  ["K", 1 << 5],
  ["P", 1 << 6],
]);
const ZH_MASK = 0b0001111;
const JA_MASK = 0b0010000;
const KO_MASK = 0b1100000;
const ALL_MASK = 0b1111111;

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(root, "src/generated/unihan-core.ts");

function isLanguageExclusive(mask) {
  return (
    (mask & ZH_MASK) === mask ||
    mask === JA_MASK ||
    (mask & KO_MASK) === mask
  );
}

function normalizeMask(mask) {
  if ((mask & (mask - 1)) === 0) return mask;
  if ((mask & ZH_MASK) === mask) return ZH_MASK;
  if ((mask & KO_MASK) === mask) return KO_MASK;
  return mask;
}

function createBitWriter() {
  const bytes = [];
  let byte = 0;
  let bitCount = 0;

  return {
    write(bit) {
      byte = (byte << 1) | bit;
      bitCount += 1;
      if (bitCount === 8) {
        bytes.push(byte);
        byte = 0;
        bitCount = 0;
      }
    },
    finish() {
      if (bitCount > 0) bytes.push(byte << (8 - bitCount));
      return Uint8Array.from(bytes);
    },
  };
}

function writeGamma(writer, value) {
  const highestBit = Math.floor(Math.log2(value));
  for (let index = 0; index < highestBit; index += 1) writer.write(0);
  for (let index = highestBit; index >= 0; index -= 1) {
    writer.write((value >> index) & 1);
  }
}

function wrapBase64(value) {
  return value.match(/.{1,100}/g).map((line) => `  "${line}"`).join(" +\n");
}

function generateSource(records, version, date) {
  const maskCounts = new Map();
  for (const [, mask] of records) {
    maskCounts.set(mask, (maskCounts.get(mask) ?? 0) + 1);
  }
  const masksByFrequency = [...maskCounts]
    .sort((left, right) => right[1] - left[1] || left[0] - right[0])
    .map(([mask]) => mask);
  if (masksByFrequency.length > 15) {
    throw new Error("The normalized region masks no longer fit in four bits");
  }
  const maskRanks = new Map(masksByFrequency.map((mask, rank) => [mask, rank]));

  const gapWriter = createBitWriter();
  const maskWriter = createBitWriter();
  let previousCodePoint = 0;

  for (const [codePoint, mask] of records) {
    const gap = codePoint - previousCodePoint;
    if (gap === 1) gapWriter.write(0);
    else {
      gapWriter.write(1);
      writeGamma(gapWriter, gap - 1);
    }

    const maskRank = maskRanks.get(mask);
    for (let index = 0; index < maskRank; index += 1) maskWriter.write(1);
    maskWriter.write(0);
    previousCodePoint = codePoint;
  }

  const gapBytes = gapWriter.finish();
  const maskBytes = maskWriter.finish();
  const bytes = new Uint8Array(gapBytes.length + maskBytes.length);
  bytes.set(gapBytes);
  bytes.set(maskBytes, gapBytes.length);
  const encoded = Buffer.from(bytes).toString("base64");

  return `// Generated by npm run update:unihan. Do not edit manually.\n` +
    `export const UNIHAN_VERSION = ${JSON.stringify(version)};\n` +
    `export const UNIHAN_DATE = ${JSON.stringify(date)};\n` +
    `export const RECORD_COUNT = ${records.length};\n` +
    `export const MIN_CODE_POINT = 0x${records[0][0].toString(16)};\n` +
    `export const MAX_CODE_POINT = 0x${records.at(-1)[0].toString(16)};\n` +
    `export const GAP_BYTE_LENGTH = ${gapBytes.length};\n` +
    `export const MASKS_BY_FREQUENCY = ${JSON.stringify(masksByFrequency)};\n` +
    `let encodedData =\n${wrapBase64(encoded)};\n` +
    `export function takeEncodedData() {\n` +
    `  const data = encodedData;\n` +
    `  encodedData = "";\n` +
    `  return data;\n` +
    `}\n`;
}

const fileArgumentIndex = process.argv.indexOf("--file");
let archiveBytes;
if (fileArgumentIndex >= 0) {
  const sourcePath = process.argv[fileArgumentIndex + 1];
  if (!sourcePath) throw new Error("--file requires a path to Unihan.zip");
  archiveBytes = new Uint8Array(await readFile(sourcePath));
} else {
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Failed to download Unihan.zip: ${response.status} ${response.statusText}`);
  }
  archiveBytes = new Uint8Array(await response.arrayBuffer());
}

const archive = unzipSync(archiveBytes);
const decoder = new TextDecoder("utf-8", { fatal: true });
const recordsByCodePoint = new Map();
const seenCodePoints = new Set();
let totalRecordCount = 0;
let version;
let date;

// Search every Unihan text file because Unicode may move a property between files.
for (const [name, contents] of Object.entries(archive)) {
  if (!/^Unihan.*\.txt$/.test(name)) continue;

  const text = decoder.decode(contents);
  version ??= text.match(/^# Unicode Version (.+)$/m)?.[1];
  date ??= text.match(/^# Date: (.+)$/m)?.[1];

  for (const line of text.split("\n")) {
    if (!line.includes("\tkUnihanCore2020\t")) continue;

    const match = /^U\+([0-9A-F]+)\tkUnihanCore2020\t([GHJKMPT]{1,7})\r?$/.exec(line);
    if (!match) throw new Error(`Invalid kUnihanCore2020 record: ${line}`);

    const codePoint = Number.parseInt(match[1], 16);
    let mask = 0;
    for (const region of match[2]) mask |= REGION_BITS.get(region);
    if (seenCodePoints.has(codePoint)) {
      throw new Error(`Duplicate kUnihanCore2020 record: U+${match[1]}`);
    }
    seenCodePoints.add(codePoint);
    totalRecordCount += 1;
    if (isLanguageExclusive(mask)) {
      // Exact multi-region combinations do not affect language or region exclusivity.
      recordsByCodePoint.set(codePoint, normalizeMask(mask));
    }
  }
}

if (!version || !date) throw new Error("Unihan version metadata was not found");
if (recordsByCodePoint.size === 0) throw new Error("No kUnihanCore2020 records were found");

const records = [...recordsByCodePoint].sort((a, b) => a[0] - b[0]);
for (const [codePoint, mask] of records) {
  if (mask === 0 || mask > ALL_MASK) throw new Error(`Invalid region mask for U+${codePoint.toString(16)}`);
}

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generateSource(records, version, date), "utf8");
console.log(
  `Updated ${records.length.toLocaleString("en-US")} language-exclusive records ` +
    `from ${totalRecordCount.toLocaleString("en-US")} Unihan ${version} records (${date}).`,
);
